on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - run: pip install ruff
    - name: linters
      run: |
        ruff mfa tests
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.8'
            django: '3.2'
          - python: '3.12'
            django: '4.2'
          - python: '3.12'
            django: '5.0'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - run: pip install . coverage tomli "django==${{ matrix.django }}"
    - name: tests
      run: |
        coverage run -m tests.manage test
        coverage report
  publish:
    needs: [lint, test]
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - run: pip install build
    - name: build
      run: python3 -m build
    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
